---

# Generate EOS Intended Configuration File
- name: Generate config files
  template: src=eos_intended_config.j2 dest=./configs/{{ inventory_hostname }}.cfg
  tags: [configs]


  # Generate Documentation in Markdown format
- name: Generate documentation file
  vars:
    switch_nodes: "{{ groups['FABRIC'] }}"
  template: src=readme.j2 dest=./docs/README.md
  tags: [docs]