type: leaf
mgmt_ip: 192.168.1.253

# MLAG
peer_link_interfaces:
  - Ethernet47
  - Ethernet48
# Define side A or side B of MLAG
mlag_side: B
mlag_peer: LEAF1A

# Define LAGs here - match A & B side Spine/Leaf YML files
lag_port_channels:
  lag_ids:
    1:
      interfaces: [Ethernet1,Ethernet2]
      device: [SPINE1,SPINE2] # for description purposes
