type: spine
mgmt_ip: 192.168.1.250

# MLAG
peer_link_interfaces:
  - Ethernet47
  - Ethernet48
# Define side A or side B of MLAG
mlag_side: A
mlag_peer: SPINE2

# Define LAGs here - match A & B side Spine/Leaf YML files
lag_port_channels:
  lag_ids:
    1:
      interfaces: [Ethernet1,Ethernet2]
      device: [LEAF1A,LEAF1B] # for description purposes
    2:
      interfaces: [Ethernet3,Ethernet4]
      device: [LEAF2A,LEAF2B] # for description purposes

